package com.gotham.newsmediabrowser.datagen.client;

import java.util.Objects;

/**
 * Immutable carrier for synthetic media assets generated by ComfyUI or Kokoro.
 */
public record GeneratedMedia(
        byte[] bytes,
        String mimeType,
        String filename,
        String title,
        String caption,
        String description,
        String altText,
        String credit
) {
    public GeneratedMedia {
        Objects.requireNonNull(bytes, "bytes must not be null");
        Objects.requireNonNull(mimeType, "mimeType must not be null");
        Objects.requireNonNull(filename, "filename must not be null");
        if (title == null) title = filename;
        if (caption == null) caption = "";
        if (description == null) description = "";
        if (altText == null) altText = "";
        if (credit == null) credit = "Synthetic AI generated";
    }

    public static GeneratedMedia simple(byte[] bytes, String mimeType, String filename, String title, String caption) {
        return new GeneratedMedia(
                bytes,
                mimeType,
                filename,
                title,
                caption,
                caption,
                caption,
                "Gotham Synthetic News Desk"
        );
    }
}
